### ISSUE TITLE
pangolin-data github tag version inconsistent with version in __init__.py

### ISSUE THREAD

**Issue by kapsakcj** [cov-lineages/pangolin#393]
Posting here since I believe the solution would have to be implemented in `pangolin` code rather than `pangolin-data` code

I have found this to be a bit confusing since these versions do not match and thus the outputs of `pangolin --update` and `pangolin --all-versions` show discrepant versions. 

This also leads to `pangolin --update` repeatedly downloading `pangolin-data` since I believe it looks at `pangolin_data/pangolin_data/__init__.py` to check which version is downloaded instead of looking at the github tag (not sure where this is info stored locally).

I built my conda environment with this YML, pinning on `pangolin-data` github tag `v1.2.133.2`

```yml
name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal<=6.8.0
  - gofasta
  - pysam==0.16.0.1
  - ucsc-fatovcf>=426
  - usher=0.5.3
  - git-lfs
  - pip:
    - git+https://github.com/cov-lineages/pangolin-data.git@v1.2.133.2
    - git+https://github.com/cov-lineages/scorpio.git@v0.3.16
    - git+https://github.com/cov-lineages/constellations.git@v0.1.4
```
and built the conda env with `micromamba create -n pangolin -y -f environment.yml`
which shows the discrepant versions:
```
[output shortened for brevity ...]

Installing pip packages: git+https://github.com/cov-lineages/pangolin-data.git@v1.2.133.2, git+https://github.com/cov-lineages/scorpio.git@v0.3.16, git+https://github.com/cov-lineages/constellations.git@v0.1.4
Collecting git+https://github.com/cov-lineages/pangolin-data.git@v1.2.133.2 (from -r /tmp/mambafuLnTpWc7Oh (line 1))
  Cloning https://github.com/cov-lineages/pangolin-data.git (to revision v1.2.133.2) to /tmp/pip-req-build-25893gg8
  Running command git clone -q https://github.com/cov-lineages/pangolin-data.git /tmp/pip-req-build-25893gg8

[...]

Successfully installed constellations-0.1.4 pangolin-data-1.2.133 scorpio-0.3.16
```
Followed by `pip install . && pangolin --add-assignment-cache` to complete the install.

So when I run `pangolin --all-versions` and `pangolin --update` and `pangolin --all-versions` again, the following happens. `pangolin --update` downloads `pangolin-data 1.2.133.2` despite it already being downloaded/installed (based on output from above)
```
(pangolin) # pangolin --all-versions
****
Pangolin running in usher mode.
****
pangolin: 4.0
pangolin-data: 1.2.133
constellations: v0.1.4
scorpio: 0.3.16
pangolin-assignment: v1.2.133

(pangolin) # pangolin --update
pangolin already latest release (v4.0)
pangolin-data updated to v1.2.133.2
constellations already latest release (v0.1.4)
scorpio already latest release (v0.3.16)
pangolin-assignment updated to v1.2.133.1

(pangolin) # pangolin --all-versions
****
Pangolin running in usher mode.
****
pangolin: 4.0
pangolin-data: 1.2.133
constellations: v0.1.4
scorpio: 0.3.16
pangolin-assignment: v1.2.133
```

Suggestions would be one of the following:
  *  Ensure that the GitHub tag used for the release exactly matches what is listed in `__init__.py` and do not switch for a different tag after making the release.
    *  Note: This would not allow for the release to be switched to a different tag and would require a bump of the version in `__init__.py` if changes had to be made (which could lead to more releases 😵 )
  * As @AngieHinrichs pondered "I wonder if there's a fancy github way to automatically update __init__.py when making a tag.  (I.e. immediately before making the tag, edit __init__.py so that version = "{tag}", commit __init__.py, then make the tag."
  * something else?
